import { TradingIdea } from '../types/ideas';

export const MOCK_IDEAS: TradingIdea[] = [
  {
    id: 'idea-1',
    title: 'BTC/USD: The Final Capitulation Before 100k',
    author: 'QuantumTrade',
    category: 'crypto',
    type: 'idea',
    summary: 'Analyzing the macro Fibonacci levels and liquidation clusters around the $60k mark.',
    imageUrl: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?q=80&w=1469&auto=format&fit=crop',
    tradingViewUrl: 'https://www.tradingview.com/chart/BTCUSD/xyz/',
    createdAt: new Date().toISOString(),
    likes: 1240,
    comments: 89,
  },
  {
    id: 'script-1',
    title: 'Neo-Brutalist RSI Oscillator',
    author: 'LazarusLab',
    category: 'stock',
    type: 'script',
    summary: 'A highly responsive RSI variant with built-in volatility filters and momentum divergence detection.',
    content: `//@version=5\nindicator("Neo-Brutalist RSI", overlay=false)\nsrc = close\nlen = input.int(14, "Length")\nup = ta.rma(math.max(ta.change(src), 0), len)\ndown = ta.rma(-math.min(ta.change(src), 0), len)\nrsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))\nplot(rsi, "RSI", color=color.new(#FF3366, 0), linewidth=3)`,
    tradingViewUrl: 'https://www.tradingview.com/script/xyz/',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    likes: 450,
    comments: 12,
  },
  {
    id: 'idea-2',
    title: 'NVDA: Post-Earnings Consolidation Phase',
    author: 'AlphaScanner',
    category: 'stock',
    type: 'idea',
    summary: 'NVDA is showing signs of exhaustion. Looking for a retest of the previous breakout zone.',
    imageUrl: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?q=80&w=1374&auto=format&fit=crop',
    tradingViewUrl: 'https://www.tradingview.com/chart/NVDA/xyz/',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    likes: 890,
    comments: 45,
  },
  {
    id: 'post-1',
    title: 'Why Macro Matters More Than Ever',
    author: 'DossierLead',
    category: 'stock',
    type: 'post',
    summary: 'In a world of high interest rates, understanding the DXY is the key to all other asset classes.',
    tradingViewUrl: 'https://www.tradingview.com/u/LazarusReport/',
    createdAt: new Date(Date.now() - 10800000).toISOString(),
    likes: 230,
    comments: 15,
  },
  {
    id: 'script-2',
    title: 'Multi-Timeframe EMA Ribbon',
    author: 'StrategyMaster',
    category: 'crypto',
    type: 'script',
    summary: 'Visualizes trend strength across 4 timeframes simultaneously. Perfect for scalping crypto volatility.',
    content: `//@version=5\nindicator("MTF EMA Ribbon", overlay=true)\nema1 = ta.ema(close, 20)\nema2 = ta.ema(close, 50)\nema3 = ta.ema(close, 100)\nplot(ema1, color=color.aqua)\nplot(ema2, color=color.blue)\nplot(ema3, color=color.navy)`,
    tradingViewUrl: 'https://www.tradingview.com/script/abc/',
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    likes: 670,
    comments: 34,
  },
];
