import type { NewsArticle } from '../types/news';

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: 'mock-1',
    title: 'Modernizing the Dossier: A Deep Dive into Information Hierarchy',
    source: 'Lazarus Report',
    summary: 'How intelligence platforms are redefining the way we consume market signals and global news in the digital age.',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1472&auto=format&fit=crop',
    contentUrl: 'https://example.com/1',
    publishedAt: new Date().toISOString(),
    provider: 'newsdata',
  },
  {
    id: 'mock-2',
    title: 'The Rise of Obsidian Design in Fintech Applications',
    source: 'Design Intelligence',
    summary: 'Dark themes are no longer just an aesthetic choice; they are a standard for high-performance dashboards and trading terminals.',
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=1632&auto=format&fit=crop',
    contentUrl: 'https://example.com/2',
    publishedAt: new Date(Date.now() - 3600000).toISOString(),
    provider: 'gnews',
  },
  {
    id: 'mock-3',
    title: 'Market Signals: Navigating the Noise of Global Finance',
    source: 'Financial Times',
    summary: 'As volatility increases, identifying the signal over the noise becomes the primary challenge for institutional investors.',
    imageUrl: 'https://images.unsplash.com/photo-1611974714480-928929c29806?q=80&w=1471&auto=format&fit=crop',
    contentUrl: 'https://example.com/3',
    publishedAt: new Date(Date.now() - 7200000).toISOString(),
    provider: 'newsapi',
  },
  {
    id: 'mock-4',
    title: 'Crypto Assets Enter a New Era of Regulatory Clarity',
    source: 'Reuters',
    summary: 'Global frameworks are emerging to provide the stability needed for mass adoption of decentralized finance.',
    imageUrl: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?q=80&w=1587&auto=format&fit=crop',
    contentUrl: 'https://example.com/4',
    publishedAt: new Date(Date.now() - 10800000).toISOString(),
    provider: 'marketaux',
  },
  {
    id: 'mock-5',
    title: 'Global Semiconductor Shortage: The End in Sight?',
    source: 'Bloomberg',
    summary: 'Supply chain experts predict a stabilization of chip production by the end of Q3, following record investments.',
    imageUrl: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?q=80&w=1374&auto=format&fit=crop',
    contentUrl: 'https://example.com/5',
    publishedAt: new Date(Date.now() - 14400000).toISOString(),
    provider: 'worldnews',
  },
];
